//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17626
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExpressionParser.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ExpressionParser.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;xs:schema xmlns:xs=&quot;http://www.w3.org/2001/XMLSchema&quot; elementFormDefault=&quot;qualified&quot;&gt;
        ///    &lt;xs:element name=&quot;Aggregation&quot;&gt;
        ///        &lt;xs:complexType&gt;
        ///            &lt;xs:sequence&gt;
        ///                &lt;xs:element ref=&quot;Lib&quot;/&gt;
        ///            &lt;/xs:sequence&gt;
        ///            &lt;xs:attribute name=&quot;Version&quot; use=&quot;required&quot; type=&quot;xs:decimal&quot;/&gt;
        ///        &lt;/xs:complexType&gt;
        ///    &lt;/xs:element&gt;
        ///    &lt;xs:element name=&quot;Lib&quot;&gt;
        ///        &lt;xs:complexType&gt;
        ///            &lt;xs:sequence&gt;
        ///                &lt;xs: [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ExternResourceDefinitionLibrarySchema {
            get {
                return ResourceManager.GetString("ExternResourceDefinitionLibrarySchema", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;Aggregation Version=&quot;1.0&quot;&gt;
        ///    &lt;Lib Name=&quot;Math&quot; Type=&quot;System.Math&quot;&gt;
        ///        &lt;Methods&gt;
        ///            &lt;Method Name=&quot;Pow&quot; Static=&quot;true&quot;&gt;
        ///                &lt;Signature&gt;
        ///                    &lt;Param Type=&quot;double&quot; /&gt;
        ///                    &lt;Param Type=&quot;double&quot; /&gt;
        ///                &lt;/Signature&gt;
        ///            &lt;/Method&gt;
        ///            &lt;Method Name=&quot;Abs&quot; Static=&quot;true&quot;&gt;
        ///                &lt;Signature&gt;
        ///                    &lt;Param Type=&quot;double&quot; /&gt;
        ///                &lt;/Signature&gt;
        ///            &lt;/Method&gt;
        ///     [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string System_Math {
            get {
                return ResourceManager.GetString("System_Math", resourceCulture);
            }
        }
    }
}
